# Generated by Django 3.2.18 on 2023-05-01 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20230419_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='reference',
        ),
    ]
