# Generated by Django 3.2.18 on 2023-05-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_remove_item_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=20),
        ),
    ]
